-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 01:57:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `user_FName` VARCHAR(45) NULL,
  `user_LName` VARCHAR(45) NULL,
  PRIMARY KEY (`UserName`));


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleName`));


-- -----------------------------------------------------
-- Table `mydb`.`UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserRoles` (
  `UserName` VARCHAR(45) NULL,
  `RoleName` VARCHAR(45) NULL,
  INDEX `UserName_idx` (`UserName` ASC) VISIBLE,
  INDEX `RoleName_idx` (`RoleName` ASC) VISIBLE,
  CONSTRAINT `UserName`
    FOREIGN KEY (`UserName`)
    REFERENCES `mydb`.`Users` (`UserName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RoleName`
    FOREIGN KEY (`RoleName`)
    REFERENCES `mydb`.`Roles` (`RoleName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `idRoom` INT(16) NOT NULL,
  `room_Name` VARCHAR(45) NULL,
  `room_Maximum` INT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `clubname` VARCHAR(45) NOT NULL,
  `numatt` INT NOT NULL,
  `event_date` DATE NULL,
  `idRoom` INT(16) NULL,
  `event_length` INT(16) NULL,
  `event_title` VARCHAR(45) NULL,
  `event_type` VARCHAR(45) NULL,
  `Description` VARCHAR(144) NULL,
  `event_guestSpeaker` VARCHAR(45) NULL,
  `event_fee` BINARY NULL,
  `event_feeAmount` INT NULL,
  `event_music` BINARY NULL,
  `event_musicType` VARCHAR(45) NULL,
  `event_food` BINARY NULL,
  `event_foodRisk` BINARY NULL,
  `event_foodCatering` BINARY NULL,
  `event_foodCaterer` VARCHAR(45) NULL,
  `event_alcohol` BINARY NULL,
  `Terms_Form` BINARY NULL,
  `Terms_CSU` BINARY NULL,
  `user_UserName` VARCHAR(45) NULL,
  INDEX `idRoom_idx` (`idRoom` ASC) VISIBLE,
  INDEX `user_UserName_idx` (`user_UserName` ASC) INVISIBLE,
  CONSTRAINT `idRoom`
    FOREIGN KEY (`idRoom`)
    REFERENCES `mydb`.`Room` (`idRoom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_UserName`
    FOREIGN KEY (`user_UserName`)
    REFERENCES `mydb`.`Users` (`UserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Users` (`UserName`, `Password`, `user_FName`, `user_LName`) VALUES ('root', 'admin', 'Sarah', 'Jones');
INSERT INTO `mydb`.`Users` (`UserName`, `Password`, `user_FName`, `user_LName`) VALUES ('BTM-club', '1234', 'BTM', 'Concordia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Roles` (`RoleName`) VALUES ('System Administrator');
INSERT INTO `mydb`.`Roles` (`RoleName`) VALUES ('System Customer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`UserRoles`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`UserRoles` (`UserName`, `RoleName`) VALUES ('root', 'System Administrator');
INSERT INTO `mydb`.`UserRoles` (`UserName`, `RoleName`) VALUES ('BTM-club', 'System Customer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Room`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Room` (`idRoom`, `room_Name`, `room_Maximum`) VALUES (001, '456', 30);
INSERT INTO `mydb`.`Room` (`idRoom`, `room_Name`, `room_Maximum`) VALUES (002, '450', 50);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Request`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Request` (`clubname`, `numatt`, `event_date`, `idRoom`, `event_length`, `event_title`, `event_type`, `Description`, `event_guestSpeaker`, `event_fee`, `event_feeAmount`, `event_music`, `event_musicType`, `event_food`, `event_foodRisk`, `event_foodCatering`, `event_foodCaterer`, `event_alcohol`, `Terms_Form`, `Terms_CSU`, `user_UserName`) VALUES ('CASA-JMSB', 40, '2000-01-01', 003, 30, 'Back to school', 'Party', 'party', 'Mr. Rick', NULL, 0, NULL, 'hiphip', NULL, NULL, NULL, 'food', NULL, NULL, NULL, '30');
INSERT INTO `mydb`.`Request` (`clubname`, `numatt`, `event_date`, `idRoom`, `event_length`, `event_title`, `event_type`, `Description`, `event_guestSpeaker`, `event_fee`, `event_feeAmount`, `event_music`, `event_musicType`, `event_food`, `event_foodRisk`, `event_foodCatering`, `event_foodCaterer`, `event_alcohol`, `Terms_Form`, `Terms_CSU`, `user_UserName`) VALUES ('Concordia Art', 50, '2019-03-03', 004, 40, 'Art', 'Show', 'art show', 'Mrs. Peters', NULL, 0, NULL, 'none', NULL, NULL, NULL, 'mcdonalds', NULL, NULL, NULL, NULL);

COMMIT;

